#!/bin/bash

myterm &

wlr-randr --output DP-3 --mode 3840x2160 --pos 3440,0 --output HDMI-A-1 --mode 3440x1440 --pos 0,567 &

# waybar &
while pgrep -x mwd; do
	myterm

	pgrep -w mwd
	if [ $? -ne 0 ]; then
		exit 0
	fi
	sleep 1
done

